version: '2'

services:
  front-end:
    image: weaveworksdemos/front-end
    hostname: front-end
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - external
      - secure
      - internal
  edge-router:
    image: weaveworksdemos/edge-router
    ports:
      - '80:80'
    hostname: edge-router
    domainname: weave.local
    restart: always
    environment:
      - "reschedule:on-node-failure"
      - "constraint:node==swarm-master"
    networks:
      - external
  catalogue:
    image: weaveworksdemos/catalogue
    hostname: catalogue
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - external
  catalogue-db:
    image: weaveworksdemos/catalogue-db
    hostname: catalogue-db
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
    networks:
      - external
  cart:
    image: weaveworksdemos/cart
    hostname: cart
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - internal
  cart-db:
    image: mongo
    hostname: cart-db
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - internal
  orders:
    image: weaveworksdemos/orders
    hostname: orders
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - internal
      - secure
      - backoffice
  orders-db:
    image: mongo
    hostname: orders-db
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - internal
  shipping:
    image: weaveworksdemos/shipping
    hostname: shipping
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - backoffice
  queue-master:
    image: weaveworksdemos/queue-master
    hostname: queue-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - backoffice
  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - backoffice
  payment:
    image: weaveworksdemos/payment
    hostname: payment
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - secure
  user:
    image: weaveworksdemos/user
    hostname: user
    domainname: weave.local
    restart: always
    environment:
      - MONGO_HOST=user-db:27017
      - reschedule:on-node-failure
    networks:
      - secure
  user-db:
    image: weaveworksdemos/user
    hostname: user-db
    domainname: weave.local
    restart: always
    environment:
      - reschedule:on-node-failure
    networks:
      - secure
  user-sim:
    image: weaveworksdemos/load-test
    hostname: user-simulator
    domainname: weave.local
    networks:
      - external
    command: "-d 60 -r 200 -c 2 -h edge-router"
networks:
  external:
    driver: weave
  secure:
    driver: weave
  internal:
    driver: weave
  backoffice:
    driver: weave
