version: '2'

services:
  front-end:
    image: weaveworksdemos/front-end
    hostname: front-end
    restart: always
    environment:
      - reschedule=on-node-failure
  edge-router:
    image: weaveworksdemos/edge-router
    ports:
      - '80:80'
    hostname: edge-router
    restart: always
    environment:
      - reschedule=on-node-failure
    links:
      - front-end:front-end
  catalogue:
    image: weaveworksdemos/catalogue
    hostname: catalogue
    restart: always
    environment:
      - reschedule=on-node-failure
  catalogue-db:
    image: weaveworksdemos/catalogue-db
    hostname: catalogue-db
    restart: always
    environment:
      - reschedule=on-node-failure
      - MYSQL_ROOT_PASSWORD=fake_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
  cart:
    image: weaveworksdemos/cart
    hostname: cart
    restart: always
    environment:
      - reschedule=on-node-failure
  cart-db:
    image: mongo
    hostname: cart-db
    restart: always
    environment:
      - reschedule=on-node-failure
  orders:
    image: weaveworksdemos/orders
    hostname: orders
    restart: always
    environment:
      - reschedule=on-node-failure
  orders-db:
    image: mongo
    hostname: orders-db
    restart: always
    environment:
      - reschedule=on-node-failure
  shipping:
    image: weaveworksdemos/shipping
    hostname: shipping
    restart: always
    environment:
      - reschedule=on-node-failure
  queue-master:
    image: weaveworksdemos/queue-master
    hostname: queue-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - reschedule=on-node-failure
  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
    restart: always
    environment:
      - reschedule=on-node-failure
  payment:
    image: weaveworksdemos/payment
    hostname: payment
    restart: always
    environment:
      - reschedule=on-node-failure
  user:
    image: weaveworksdemos/user
    hostname: user
    restart: always
    environment:
      - MONGO_HOST=user-db:27017
      - reschedule=on-node-failure
  user-db:
    image: weaveworksdemos/user-db
    hostname: user-db
    restart: always
    environment:
      - reschedule=on-node-failure
  user-sim:
    image: weaveworksdemos/load-test
    hostname: user-simulator
    command: "-d 60 -r 200 -c 2 -h edge-router"

