---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  labels:
    app: orders-db
    service: orders-db
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 27017
    name: mongo
    targetPort: 27017
  selector:
    app: orders-db
