global:
  # The default SMTP smarthost used for sending emails.
  smtp_smarthost: 'smtp.gmail.com:587'
  # SMTP authentication information.
  smtp_auth_username: ''
  smtp_auth_password: ''
  # The default SMTP From header field.
  smtp_from: 'alertmanager@example.org'

route:
  group_by: ['cluster']
  receiver: email-all
  # Zero or more child routes.
  routes:
    # A set of equality matchers an alert has to fulfill to match the node.
    - match:
        severity: email
      receiver: email-all
receivers:
  # The unique name of the receiver.
- name: 'email-all'
  email_configs:
    # The email address to send notifications to.
  - to: 'alertmanager@example.org'
    # Whether or not to notify about resolved alerts.
    send_resolved: true
    # The HTML body of the email notification.
    html: '{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}'
