version: '2'

services:
  front-end:
    image: weaveworksdemos/front-end
    hostname: front-end
    restart: always
    cap_drop:
      - all
    read_only: true
    environment:
      - reschedule=on-node-failure
  edge-router:
    image: weaveworksdemos/edge-router
    ports:
      - '80:80'
    hostname: edge-router
    restart: always
    environment:
      - reschedule=on-node-failure
  catalogue:
    image: weaveworksdemos/catalogue:snapshot
    hostname: catalogue
    restart: always
    environment:
      - ZIPKIN=http://zipkin:9411/api/v1/spans
  catalogue-db:
    image: weaveworksdemos/catalogue-db
    hostname: catalogue-db
    restart: always
    environment:
      - reschedule=on-node-failure
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
  cart:
    image: weaveworksdemos/cart
    hostname: cart
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - reschedule=on-node-failure
  cart-db:
    image: mongo
    hostname: cart-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - reschedule=on-node-failure
  orders:
    image: weaveworksdemos/orders
    hostname: orders
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - reschedule=on-node-failure
  orders-db:
    image: mongo
    hostname: orders-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - reschedule=on-node-failure
  shipping:
    image: weaveworksdemos/shipping
    hostname: shipping
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - reschedule=on-node-failure
  queue-master:
    image: weaveworksdemos/queue-master
    hostname: queue-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - reschedule=on-node-failure
  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: true
    environment:
      - reschedule=on-node-failure
  payment:
    image: weaveworksdemos/payment
    hostname: payment
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    environment:
      - reschedule=on-node-failure
  user:
    image: weaveworksdemos/user:snapshot
    hostname: user
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    environment:
      - MONGO_HOST=user-db:27017
      - ZIPKIN=http://zipkin:9411/api/v1/spans
      - reschedule=on-node-failure
  user-db:
    image: weaveworksdemos/user-db
    hostname: user-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - reschedule=on-node-failure
  user-sim:
    image: weaveworksdemos/load-test
    cap_drop:
      - all
    read_only: true
    hostname: user-simulator
    command: "-d 60 -r 200 -c 2 -h edge-router"
  zipkin:
    image: openzipkin/zipkin 
    hostname: zipkin
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - reschedule=on-node-failure
    ports:
      - "9411:9411"
